### ISSUE TITLE
[RFC] change error type

### ISSUE THREAD

**Issue by Luro02** [sile/hls_m3u8#13]
I think trackable should be replaced by a "normal" implementation of an error-type, like for example the one, that can be found in reqwest; https://github.com/seanmonstar/reqwest/blob/d7fcd8ac2ec69fe2e4eb46c6589253f73a8b2d10/src/error.rs#L56

### 1. Parts of the code are hard to read, because of `track!()`
Each time a function returns an error it has to be wrapped in the `track!()`-macro, which can make it very hard to read parts of code:
``` rust
let value = track!(Value::new(track!(parse_u64("123"))?))?;
// vs
let value = Value::new(parse_u64("123")?)?;
```

### 2. It's easy to forget a `track!()`
It's easy to forget wrapping a result in `track!()`, instead of just returning it.
``` rust
let value = track!(Value::new(parse_u64("123")?))?;
```
### 3. Tests could be better
It isn't possible to compare errors directly (because of missing trait implementations), so you have to compare via `is_ok` or `is_err`, but this causes the tests to succeed, if any part of the tested code returns an error, so you can't specifically test for one kind of error.
```rust
assert_eq!(text.parse().ok(), Some(tag.clone()));
```

**Comment by sile** [comment]
Thank you for your RFC.

I think your proposal is reasonable.
I like `trackable` because it can provide compact backtrace when an error happens. Also, it provides handy assertion macros such as `track_panic!()`. However, at the same time, I recognize it has the drawbacks that you pointed out. 
So, it's okay to change error type.

FYI. [`failure`](https://github.com/rust-lang-nursery/failure) crate seems a popular error handling crate in Rust community (I'm not familiar with it though).
